### ISSUE TITLE
Tools for Images

### ISSUE THREAD

**Issue by angoodkind** [neoben/smart-fancy-latex-cv#1]
Do you have references for the tools you used to make the images?

**Comment by neoben** [comment]
Hi,
I used Google drive and GIMP.

On Jan 14, 2017 16:31, "Adam Goodkind" <notifications@github.com> wrote:

Do you have references for the tools you used to make the images?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/neoben/smart-fancy-latex-cv/issues/1>, or mute the
thread

**Comment by angoodkind** [comment]
Thanks
